import { CANONICAL_ASSET_MANIFEST_VERSION, CANONICAL_CONTENT_VERSION, CANONICAL_RULESET_VERSION } from "@auto-battler/game-core";
interface Room { readonly roomId: string; readonly players: readonly string[]; readonly region: string; readonly mode: string; readonly maxPlayers: 8; readonly phase: "PREPARE"; readonly rulesetVersion: typeof CANONICAL_RULESET_VERSION; readonly contentVersion: typeof CANONICAL_CONTENT_VERSION; readonly assetManifestVersion: typeof CANONICAL_ASSET_MANIFEST_VERSION; lease: { fencingToken: number; readonly acquiredAt: number }; readonly commandIds: Set<string>; readonly combatIds: Set<string>; }
export function createRoomRegistry(options: { readonly now?: () => number }) {
  const now = options.now ?? Date.now;
  const rooms = new Map<string, Room>();
  return Object.freeze({
    create(input: { readonly roomId: string; readonly players: readonly string[]; readonly region: string; readonly mode: string }): Omit<Room, "commandIds" | "combatIds"> { if (input.players.length !== 8 || new Set(input.players).size !== 8) throw new Error("ROOM_REQUIRES_EIGHT_PLAYERS"); const room: Room = { ...input, maxPlayers: 8, phase: "PREPARE", rulesetVersion: CANONICAL_RULESET_VERSION, contentVersion: CANONICAL_CONTENT_VERSION, assetManifestVersion: CANONICAL_ASSET_MANIFEST_VERSION, lease: { fencingToken: 1, acquiredAt: now() }, commandIds: new Set(), combatIds: new Set() }; rooms.set(input.roomId, room); return roomView(room); },
    get(roomId: string): Omit<Room, "commandIds" | "combatIds"> | undefined { const room = rooms.get(roomId); return room === undefined ? undefined : roomView(room); },
    acceptCommand(roomId: string, input: { readonly fencingToken: number; readonly commandId: string; readonly playerId: string; readonly type: "READY" }): { readonly accepted: boolean; readonly reason?: string } { const room = rooms.get(roomId); if (room === undefined) throw new Error("ROOM_NOT_FOUND"); if (input.fencingToken !== room.lease.fencingToken) return { accepted: false, reason: "FENCING_TOKEN_STALE" }; if (!room.players.includes(input.playerId)) return { accepted: false, reason: "PLAYER_NOT_IN_ROOM" }; if (room.commandIds.has(input.commandId)) return { accepted: false, reason: "DUPLICATE_COMMAND" }; room.commandIds.add(input.commandId); return { accepted: true }; },
    recordCombatResult(roomId: string, input: { readonly combatId: string; readonly resultHash: string }): boolean { const room = rooms.get(roomId); if (room === undefined) throw new Error("ROOM_NOT_FOUND"); if (room.combatIds.has(input.combatId)) return false; room.combatIds.add(input.combatId); return true; },
    recover(roomId: string, input: { readonly fencingToken: number }): Omit<Room, "commandIds" | "combatIds"> { const room = rooms.get(roomId); if (room === undefined) throw new Error("ROOM_NOT_FOUND"); if (input.fencingToken !== room.lease.fencingToken) throw new Error("FENCING_TOKEN_STALE"); room.lease = { fencingToken: room.lease.fencingToken + 1, acquiredAt: now() }; return roomView(room); },
  });
}
function roomView(room: Room): Omit<Room, "commandIds" | "combatIds"> { const { commandIds: _commands, combatIds: _combats, ...view } = room; return view; }
